name: Conditional env 

on:
    push:
      branches: [ "main" ]
  

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ vars.IMAGE_TAG == '0.0.1' }}
        run: echo $First_Name. Today is MERDA!"
        env:
          First_Name: Mona
